"""Initial migration

Revision ID: 28772f3b4b1b
Revises: 
Create Date: 2024-07-27 23:45:13.032879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28772f3b4b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=True),
    sa.Column('short_url', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Url')
    # ### end Alembic commands ###
